#!/bin/bash

# Directory containing the original pictures
original_dir="./lab04_raw_files"

# Destination directory
dest_dir="./new_images"

# Create destination directory if needed
if [ ! -d "$rename_dir" ] ; then
	mkdir -p $dest_dir
fi

# Loop throught files
for file in "$original_dir"/* ; do

        # Check it is an image 
        if [[ "${file##*.}" =~ ^(png|jpg)$ ]] ; then

                # Create the new namw
                new_name="${file##*/}"
		dim=$(identify -format '_%w_%h' $file)
		new_name=$(echo $new_name | sed "s/\./$dim&/g")

		# Copy the file
		cp $file $dest_dir/$new_name
        fi
done
