#!/bin/bash

# Define target directory
target_dir="./lab04_raw_files"


# Test if the directory exist
if [ ! -d "$target_dir" ] ; then
	exit 1
fi


# Loop throught file
for file in "$target_dir"/* ; do
	# Check it is an image 
	if [[ "${file##*.}" =~ ^(png|jpg)$ ]] ; then
		# print info
		echo "${file##*/} $(identify -format '%wx%h' $file)"
	fi
done

